<?php
/**
 * scripts/ftp_deploy.php
 *
 * Uploads the Energie web app to a remote FTP server, then runs pending DB
 * migrations via a temporary self-deleting PHP runner served from the webroot.
 *
 * Reads credentials from Energie/config.yaml (generated by mcp/generate.py).
 * Regenerate for the desired target before running:
 *
 *   python3 ../mcp/generate.py --app energie --target world4you
 *   php scripts/ftp_deploy.php
 *
 * Mirrors wlmonitor/scripts/ftp_deploy.php — see that file for the origin of
 * the composer --no-dev autoloader guard and the migration runner pattern.
 */

$root = dirname(__DIR__);
require_once $root . '/inc/yaml.php';

$cfg = wl_yaml_load($root . '/config.yaml');

$deploy = $cfg['deploy'] ?? [];
foreach (['ftp_host', 'ftp_user', 'ftp_password', 'ftp_base_dir'] as $k) {
    if (empty($deploy[$k])) {
        fwrite(STDERR, "config.yaml is missing deploy.$k — regenerate with mcp/generate.py --app energie --target world4you\n");
        exit(1);
    }
}

$ftpServer  = $deploy['ftp_host'];
$ftpUser    = $deploy['ftp_user'];
$ftpPass    = $deploy['ftp_password'];
$remoteBase = rtrim($deploy['ftp_base_dir'], '/');
$baseUrl    = rtrim($cfg['app']['base_url'] ?? '', '/');
$target     = $cfg['target'] ?? 'world4you';

if ($baseUrl === '') {
    fwrite(STDERR, "config.yaml is missing app.base_url\n");
    exit(1);
}

// ── Regenerate composer autoloader without dev deps ──────────────────────────
// Defensive: Energie currently has no require-dev, so --no-dev is a no-op, but
// the guard matches wlmonitor's pattern so it stays correct if dev deps are
// added later. Upload the prod autoloader, restore dev autoloader at shutdown.

$composerBin = null;
foreach ([
    getenv('HOME') . '/bin/composer',
    '/opt/homebrew/bin/composer',
    '/usr/local/bin/composer',
    $root . '/composer.phar',
] as $cand) {
    if (is_executable($cand) || is_readable($cand)) { $composerBin = $cand; break; }
}
if ($composerBin === null) {
    fwrite(STDERR, "composer not found — install it or adjust ftp_deploy.php\n");
    exit(1);
}

function run_composer(string $bin, string $cwd, array $args): int {
    // composer.phar must be run via php; native binaries run directly.
    $cmd = str_ends_with($bin, '.phar') ? array_merge(['php', $bin], $args) : array_merge([$bin], $args);
    $descriptors = [0 => ['pipe', 'r'], 1 => STDOUT, 2 => STDERR];
    $proc = proc_open($cmd, $descriptors, $pipes, $cwd);
    if (!is_resource($proc)) return 1;
    fclose($pipes[0]);
    return proc_close($proc);
}

echo "Dumping prod autoloader (--no-dev) ...\n";
if (run_composer($composerBin, $root, ['dump-autoload', '--no-dev', '-o']) !== 0) {
    fwrite(STDERR, "composer dump-autoload --no-dev failed\n");
    exit(1);
}

register_shutdown_function(function () use ($root, $composerBin) {
    echo "\nRestoring dev autoloader ...\n";
    run_composer($composerBin, $root, ['dump-autoload', '-o']);
});

// ── Exclude rules ─────────────────────────────────────────────────────────────
//
// scripts/    — deploy tooling doesn't belong on a web server
// scrapes/    — local raw grid-operator CSVs, never uploaded
// data/       — runtime state (ratelimit.json); world4you creates its own
// deploy/     — legacy deploy.sh
// logs/       — local runtime logs
// _Archiv/    — historical junk
// config/     — unused legacy dir
// config.*    — secrets and templates; world4you has its own config.yaml
// *.py        — Python pipeline is local-only (grid CSV import)
// CLAUDE.md / README.md / update.md — docs, excluded via .md extension
// composer.json / composer.lock / composer.phar — prod uses vendor/ as-is
// vendor dev-only packages — defensive parity with wlmonitor
// migrations/ — not present in Energie yet; left in case it gets added

$excludeDirs = [
    // project dirs not needed on server (matched at any depth by basename)
    '.git', '.claude', 'tests', '_Archiv', 'Archiv', 'docs', 'deploy',
    'config', 'data', 'logs', 'scrapes', 'backups', '.worktrees', 'worktrees',
    '__pycache__', 'node_modules', 'scripts',
    // dev-only vendor packages (mirrors wlmonitor)
    'phpunit', 'sebastian', 'nikic', 'theseer', 'phar-io', 'myclabs', 'staabm',
    // vendor CLI binaries
    'bin',
];
$excludeRootDirs = [];

$excludeNames = [
    '.gitignore', '.DS_Store', '.phpunit.result.cache',
    'CLAUDE.md', 'phpunit.xml',
    'composer.json', 'composer.lock', 'composer.phar',
    'config.yaml', 'config.example.yaml',
    'config.ini', 'config.ini.example',
    'update.md',
    'energie.py',
];
$excludeExts = ['md', 'py', 'pyc'];

// ── Connect ───────────────────────────────────────────────────────────────────

echo "Connecting to $ftpServer ...\n";
$ftp = ftp_ssl_connect($ftpServer) ?: ftp_connect($ftpServer);
if (!$ftp) {
    fwrite(STDERR, "Could not connect to $ftpServer.\n");
    exit(1);
}
if (!ftp_login($ftp, $ftpUser, $ftpPass)) {
    fwrite(STDERR, "FTP login failed for user $ftpUser.\n");
    exit(1);
}
ftp_pasv($ftp, true);
echo "Connected. Target: $remoteBase ($target)\n\n";

// ── Helpers ───────────────────────────────────────────────────────────────────

function ftp_mkdirs(mixed $ftp, string $remotePath): void {
    $parts = explode('/', trim($remotePath, '/'));
    $path  = '';
    foreach ($parts as $part) {
        $path .= '/' . $part;
        @ftp_mkdir($ftp, $path);
    }
}

function upload_tree(
    mixed  $ftp,
    string $localDir,
    string $remoteDir,
    string $relPath,
    array  $excludeDirs,
    array  $excludeRootDirs,
    array  $excludeNames,
    array  $excludeExts,
    int    &$uploaded,
    int    &$failed
): void {
    ftp_mkdirs($ftp, $remoteDir);

    foreach (scandir($localDir) as $item) {
        if ($item === '.' || $item === '..') continue;

        $localPath  = $localDir  . '/' . $item;
        $remotePath = $remoteDir . '/' . $item;
        $itemRel    = $relPath === '' ? $item : $relPath . '/' . $item;

        if (is_dir($localPath)) {
            if (in_array($item, $excludeDirs, true)) continue;
            if ($relPath === '' && in_array($item, $excludeRootDirs, true)) continue;
            upload_tree(
                $ftp, $localPath, $remotePath, $itemRel,
                $excludeDirs, $excludeRootDirs, $excludeNames, $excludeExts,
                $uploaded, $failed
            );
        } else {
            if (in_array($item, $excludeNames, true)) continue;
            if (in_array(pathinfo($item, PATHINFO_EXTENSION), $excludeExts, true)) continue;

            if (ftp_put($ftp, $remotePath, $localPath, FTP_BINARY)) {
                echo "  ok  $remotePath\n";
                $uploaded++;
            } else {
                fwrite(STDERR, "  FAIL $remotePath\n");
                $failed++;
            }
        }
    }
}

// ── Upload files ──────────────────────────────────────────────────────────────

$uploaded = 0;
$failed   = 0;

upload_tree(
    $ftp, $root, $remoteBase, '',
    $excludeDirs, $excludeRootDirs, $excludeNames, $excludeExts,
    $uploaded, $failed
);

// ── Upload config.yaml explicitly (excluded from tree walk above) ─────────────
// Without config.yaml the server cannot read DB credentials. It lives one level
// above the webroot so it is not web-accessible.

if (ftp_put($ftp, $remoteBase . '/config.yaml', $root . '/config.yaml', FTP_BINARY)) {
    echo "  ok  $remoteBase/config.yaml\n";
    $uploaded++;
} else {
    fwrite(STDERR, "  FAIL $remoteBase/config.yaml (deploy cannot work without this)\n");
    $failed++;
}

// ── Upload temporary migration runner ─────────────────────────────────────────
// Self-contained: reads ../config.yaml via inc/yaml.php on the server, runs
// pending migrations from migrations/ (if present), self-deletes.

$token = bin2hex(random_bytes(16));

$runner = <<<'RUNNER'
<?php
if (($_GET['t'] ?? '') !== '__TOKEN__') { http_response_code(403); exit; }
$r = dirname(__DIR__);
require_once $r . '/inc/yaml.php';
$cfg = wl_yaml_load($r . '/config.yaml');
$db  = $cfg['db'];
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
$con = mysqli_connect($db['host'], $db['user'], $db['password'], $db['name']);
mysqli_set_charset($con, 'utf8');
$con->query("CREATE TABLE IF NOT EXISTS db_migrations (
    name VARCHAR(255) NOT NULL PRIMARY KEY,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)");
$applied = [];
$res = $con->query('SELECT name FROM db_migrations');
while ($row = $res->fetch_assoc()) $applied[$row['name']] = true;
$files = glob($r . '/migrations/*.sql') ?: []; sort($files); $ran = 0;
foreach ($files as $file) {
    $name = basename($file);
    if (isset($applied[$name])) { echo "skip $name\n"; continue; }
    $sql = file_get_contents($file);
    $con->multi_query($sql);
    do { if ($result = $con->store_result()) $result->free(); }
    while ($con->more_results() && $con->next_result());
    $stmt = $con->prepare('INSERT INTO db_migrations (name) VALUES (?)');
    $stmt->bind_param('s', $name); $stmt->execute(); $stmt->close();
    echo "apply $name\n"; $ran++;
}
echo $ran === 0 ? "Nothing to migrate.\n" : "$ran migration(s) applied.\n";
unlink(__FILE__);
RUNNER;

$runner = str_replace('__TOKEN__', $token, $runner);
$tmp = tempnam(sys_get_temp_dir(), 'en_');
file_put_contents($tmp, $runner);

$runnerRemote = $remoteBase . '/web/_m.php';
if (ftp_put($ftp, $runnerRemote, $tmp, FTP_BINARY)) {
    echo "  ok  $runnerRemote (migration runner)\n";
}
unlink($tmp);

ftp_close($ftp);

// ── Trigger migration runner via HTTP ─────────────────────────────────────────
// Uses a stream context that skips TLS peer verification — the local Mac CA
// bundle is often incomplete and the wlmonitor deploy silently fails here
// without this. Tries https first, falls back to http.

$ctx = stream_context_create([
    'ssl'  => ['verify_peer' => false, 'verify_peer_name' => false],
    'http' => ['timeout' => 60, 'follow_location' => 1],
]);

echo "\nRunning migrations on server ...\n";
$urls = [$baseUrl . '/_m.php?t=' . $token];
if (str_starts_with($baseUrl, 'https://')) {
    $urls[] = 'http://' . substr($baseUrl, 8) . '/_m.php?t=' . $token;
}
$response = false;
foreach ($urls as $url) {
    $response = @file_get_contents($url, false, $ctx);
    if ($response !== false) { echo "  ($url)\n"; break; }
    fwrite(STDERR, "  could not reach $url, trying next ...\n");
}
if ($response !== false) {
    foreach (explode("\n", trim($response)) as $line) {
        echo "  $line\n";
    }
} else {
    fwrite(STDERR, "  Warning: migration runner could not be triggered.\n");
    fwrite(STDERR, "  Run this once in a browser: $baseUrl/_m.php?t=$token\n");
}

echo "\nDone. $uploaded uploaded" . ($failed ? ", $failed FAILED" : '') . ".\n";
if ($failed > 10) exit(1); // only hard-fail if many errors, not occasional FTP hiccups
