<?php
/**
 * scripts/ssh_deploy.php
 *
 * Rsync-over-SSH deploy for Energie, with local composer --no-dev dance and
 * remote migrations run directly via php84 over SSH (no web round-trip).
 *
 * Reads credentials from Energie/config.yaml (generated by mcp/generate.py).
 * Regenerate for the desired target before running:
 *
 *   python3 ../mcp/generate.py --app energie --target world4you
 *   php scripts/ssh_deploy.php
 *
 * Why this exists in parallel to ftp_deploy.php:
 *   - SSH runs migrations via `php84` directly — no self-deleting web runner,
 *     no DNS/vhost dependency, no stream_context TLS hacks.
 *   - Rsync is a delta transfer: after the first push, subsequent deploys
 *     only move changed bytes.
 */

$root = dirname(__DIR__);
require_once $root . '/inc/yaml.php';

$cfg = wl_yaml_load($root . '/config.yaml');

$deploy = $cfg['deploy'] ?? [];
foreach (['ssh_host', 'ssh_user', 'ssh_key', 'ftp_base_dir'] as $k) {
    if (empty($deploy[$k])) {
        fwrite(STDERR, "config.yaml is missing deploy.$k — regenerate with mcp/generate.py --app energie --target world4you\n");
        exit(1);
    }
}

$sshHost = $deploy['ssh_host'];
$sshUser = $deploy['ssh_user'];
$sshPort = (int) ($deploy['ssh_port'] ?? 22);
$sshKey  = preg_replace('#^~#', getenv('HOME') ?: '', $deploy['ssh_key']);
$target  = $cfg['target'] ?? 'world4you';

// World4you layout: the FTP path /jardyx.com/energie/ lives at
// ~/web/jardyx.com/energie/ over SSH. We reuse ftp_base_dir so generate.py
// doesn't need a separate ssh_base_dir key.
$remoteBase = 'web' . rtrim($deploy['ftp_base_dir'], '/');

$sshOpts = [
    '-i', $sshKey,
    '-p', (string) $sshPort,
    '-o', 'IdentitiesOnly=yes',
    '-o', 'BatchMode=yes',
    '-o', 'StrictHostKeyChecking=accept-new',
];
$sshTarget = $sshUser . '@' . $sshHost;
$sshCmd    = 'ssh ' . implode(' ', array_map('escapeshellarg', $sshOpts));

// ── Regenerate composer autoloader without dev deps ──────────────────────────
// Mirrors ftp_deploy.php: vendor/ is synced as-is, so the autoloader must not
// reference phpunit/deep-copy/etc. Dump prod autoloader, restore dev at shutdown.

$composerBin = null;
foreach ([
    getenv('HOME') . '/bin/composer',
    '/opt/homebrew/bin/composer',
    '/usr/local/bin/composer',
    $root . '/composer.phar',
] as $cand) {
    if (is_executable($cand) || is_readable($cand)) { $composerBin = $cand; break; }
}
if ($composerBin === null) {
    fwrite(STDERR, "composer not found — install it or adjust ssh_deploy.php\n");
    exit(1);
}

function run_proc(array $cmd, ?string $cwd = null): int {
    $descriptors = [0 => ['pipe', 'r'], 1 => STDOUT, 2 => STDERR];
    $proc = proc_open($cmd, $descriptors, $pipes, $cwd);
    if (!is_resource($proc)) return 1;
    fclose($pipes[0]);
    return proc_close($proc);
}

function run_composer(string $bin, string $cwd, array $args): int {
    $cmd = str_ends_with($bin, '.phar') ? array_merge(['php', $bin], $args) : array_merge([$bin], $args);
    return run_proc($cmd, $cwd);
}

echo "Dumping prod autoloader (--no-dev) ...\n";
if (run_composer($composerBin, $root, ['dump-autoload', '--no-dev', '-o']) !== 0) {
    fwrite(STDERR, "composer dump-autoload --no-dev failed\n");
    exit(1);
}

register_shutdown_function(function () use ($root, $composerBin) {
    echo "\nRestoring dev autoloader ...\n";
    run_composer($composerBin, $root, ['dump-autoload', '-o']);
});

// ── Rsync over SSH ───────────────────────────────────────────────────────────
// Excludes mirror ftp_deploy.php's list. Rsync matches exclude patterns at any
// path depth unless anchored with a leading slash.

$rsyncExcludes = [
    '.git/',
    '.gitignore',
    '.DS_Store',
    '.claude/',
    '.claude.json',
    '.phpunit.result.cache',
    '.worktrees/',
    'worktrees/',
    'CLAUDE.md',
    '*.md',
    'phpunit.xml',
    'composer.json',
    'composer.lock',
    'composer.phar',
    // config.yaml is NOT excluded — the local copy is the freshly-generated
    // source of truth; letting rsync sync it normally avoids the
    // --delete-excluded pitfall (which would delete the remote copy).
    'config.example.yaml',
    'config.ini',
    'config.ini.example',
    'tests/',
    'docs/',
    'deploy/',
    '_Archiv/',
    'Archiv/',
    'scripts/',
    'config/',
    'data/',
    'logs/',
    'scrapes/',
    'backups/',
    '__pycache__/',
    '*.pyc',
    '*.py',
    'node_modules/',
    // vendor dev-only packages
    'vendor/phpunit/',
    'vendor/sebastian/',
    'vendor/nikic/',
    'vendor/theseer/',
    'vendor/phar-io/',
    'vendor/myclabs/',
    'vendor/staabm/',
    'vendor/bin/',
];

echo "Rsyncing to {$sshTarget}:{$remoteBase} ...\n";
// --delete removes extraneous files on remote. Without --delete-excluded, rsync
// leaves excluded paths alone — which is what we want for runtime directories
// like scrapes/, _Archiv/, data/ that exist only on the server.
$rsyncCmd = ['rsync', '-avz', '--delete', '--copy-links'];
foreach ($rsyncExcludes as $p) {
    $rsyncCmd[] = '--exclude=' . $p;
}
$rsyncCmd[] = '-e';
$rsyncCmd[] = $sshCmd;
$rsyncCmd[] = rtrim($root, '/') . '/';
$rsyncCmd[] = $sshTarget . ':' . $remoteBase . '/';

if (run_proc($rsyncCmd) !== 0) {
    fwrite(STDERR, "rsync failed\n");
    exit(1);
}

// ── Run migrations via SSH + php84 ───────────────────────────────────────────
// Self-contained migration runner, piped to the server over stdin. Writes to
// /tmp/en_m_<rand>.php, executes with php84, removes. No web endpoint, no
// token, no DNS dependency.

$runner = <<<'PHP'
<?php
$r = getenv('ENERGIE_ROOT');
require_once $r . '/inc/yaml.php';
$cfg = wl_yaml_load($r . '/config.yaml');
$db  = $cfg['db'];
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
$con = mysqli_connect($db['host'], $db['user'], $db['password'], $db['name']);
mysqli_set_charset($con, 'utf8');
$con->query("CREATE TABLE IF NOT EXISTS db_migrations (
    name VARCHAR(255) NOT NULL PRIMARY KEY,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)");
$applied = [];
$res = $con->query('SELECT name FROM db_migrations');
while ($row = $res->fetch_assoc()) $applied[$row['name']] = true;
$files = glob($r . '/migrations/*.sql') ?: []; sort($files); $ran = 0;
foreach ($files as $file) {
    $name = basename($file);
    if (isset($applied[$name])) { echo "skip $name\n"; continue; }
    $sql = file_get_contents($file);
    $con->multi_query($sql);
    do { if ($result = $con->store_result()) $result->free(); }
    while ($con->more_results() && $con->next_result());
    $stmt = $con->prepare('INSERT INTO db_migrations (name) VALUES (?)');
    $stmt->bind_param('s', $name); $stmt->execute(); $stmt->close();
    echo "apply $name\n"; $ran++;
}
echo $ran === 0 ? "Nothing to migrate.\n" : "$ran migration(s) applied.\n";
PHP;

echo "\nRunning migrations on server ...\n";
$tmpRemote = '/tmp/en_m_' . bin2hex(random_bytes(8)) . '.php';
$remoteScript = sprintf(
    'cat > %s && ENERGIE_ROOT=%s /usr/bin/php84 %s; rc=$?; rm -f %s; exit $rc',
    escapeshellarg($tmpRemote),
    escapeshellarg($remoteBase),
    escapeshellarg($tmpRemote),
    escapeshellarg($tmpRemote)
);

$sshRun = array_merge(['ssh'], $sshOpts, [$sshTarget, $remoteScript]);
$descriptors = [0 => ['pipe', 'r'], 1 => STDOUT, 2 => STDERR];
$proc = proc_open($sshRun, $descriptors, $pipes);
if (!is_resource($proc)) {
    fwrite(STDERR, "could not start ssh for migration runner\n");
    exit(1);
}
fwrite($pipes[0], $runner);
fclose($pipes[0]);
$rc = proc_close($proc);
if ($rc !== 0) {
    fwrite(STDERR, "migration runner exited with status $rc\n");
    exit($rc);
}

echo "\nDone.\n";
